#ifndef SRC_MAINPAGE_H_
#define SRC_MAINPAGE_H_
/*! \mainpage My Personal Index Page
   * Copyright 2019 Kadin Schermers
   * \section intro_sec Introduction
   *
   * 			Kadins Lab07 landing page
   *
   * This is the documentation that has been auto-generated by doxygen for lab07 for csci3081
   *
   */

#endif  // SRC_MAINPAGE_H_
