/*! \mainpage My Personal Index Page
   *
   * \section intro_sec Introduction
   *
   * 			Kadins Lab07 landing page
   *
   * This is the documentation that has been auto-generated by doxygen for lab07 for csci3081
   *
   */
